### ISSUE TITLE
Can not switch back to default UI from Classic UI

### ISSUE THREAD

**Issue by sekanderb** [tareq1988/wedocs-plugin#1]
When I am on the default UI, I can change to Classic UI from the bottom. But after that, to get back to the default UI I have to click on the docs menu on the left. Even reloading the page does not work.

Also the switcher visibility should be improved.

**Comment by tareq1988** [comment]
wontfix

**Comment by cscholz** [comment]
Same issue for me. How can I switch back from the classic ui?

**Comment by tareq1988** [comment]
Just click on the admin menu?

**Comment by cscholz** [comment]
I'm not sure what you mean. There is no option on the left menu to switch back the view.
