### ISSUE TITLE
Load CSS and JS files only for Docs 

### ISSUE THREAD

**Issue by psahalot** [tareq1988/wedocs-plugin#104]
Hi @tareq1988 

I noticed that the plugin currently loads CSS and JS files globally.
This can be restricted to docs archive and singular docs templates.

**Comment by tareq1988** [comment]
I've been meaning to add this feature for a while, will add it soon :)

**Comment by psahalot** [comment]
Thanks for including this one in the latest update! :)

**Comment by tareq1988** [comment]
My pleasure :)
