### ISSUE TITLE
Feature Request: Share articles between docs

### ISSUE THREAD

**Issue by mrme44** [tareq1988/wedocs-plugin#13]
We have different documentation groups for different departments, but there is a lot of overlap between them. It would be nice if we could have the same article appear in multiple documentation groups. Perhaps if there was a metabox when editing an article that allowed us to choose which group and sections the article appears under.

**Comment by tareq1988** [comment]
A doc can only have one parent doc, so it can't be shared technically. You could create a common documentation and reference it elsewhere.

**Comment by enventa** [comment]
That's a pity! I also think this would be a nice and helpful feature.
