### ISSUE TITLE
Convert HTML single-page file into multiple pages with WeDoc structure

### ISSUE THREAD

**Issue by jjj-alt** [tareq1988/wedocs-plugin#138]
> Hello,
> I need to import massively my archive.
However, each document is structured in a single HTML page, and WeDocs does not recognize their gerarchy automatically.
> 
> I have tried the suggested "nextpage" tag but it does not serve the same purpose, pages do not appear in the ToC in the left column. I have browsed the support/issue section both in Wordpress and here in GitHub. Some ask how to turn multiple docs into one page but not the other way around.
> 
> Has anyone had the same problem?
Is there an existing script or additional WordPress plugin which recognizes the HTML title structure and creates a new page for each title and text block accordingly?
> 
> Any suggestion is appreciated.
> Thank you in advance

EDIT. @tareq1988  has anyone ever contacted you with the same issue before? Do you have any tips about this problem.
Thank you in advance!

**Comment by tareq1988** [comment]
> Is there an existing script or additional WordPress plugin which recognizes the HTML title structure and creates a new page for each title and text block accordingly?

You're importing HTML pages into WordPress as I understand, in this case I guess you could hire a developer to do this. weDocs has nothing to do anything with this, it expects the formatting and things a normal WordPress post would have. Importing features is totally different which weDocs offers.
