### ISSUE TITLE
Every page besides wedocs home ends up as 404

### ISSUE THREAD

**Issue by joomapp** [tareq1988/wedocs-plugin#22]
Hi Tareq,

After installing the plugin and configurating some docs all these pages ending up as 404 or redirecting to the main homepage of the website.
I have tried it on a fresh wordpress 4.6.1 / php5.6 installation with default template as sole plugin and as well as on my live website with x-theme and a lot of plugins enabled (i can share login details)

Jasper

**Comment by joomapp** [comment]
Ah, after re-saving the permalinks config panel (not changing anything though) it works now.

**Comment by geometrikal** [comment]
I had the same problem, maybe this should be prominent in the docs or on the page?

**Comment by Matt2012** [comment]
+1 saving permalinks also fixed issue.
