### ISSUE TITLE
SEO friendly permalinks

### ISSUE THREAD

**Issue by Sher-Chowdhury** [tareq1988/wedocs-plugin#29]
Hi tareq1988,

Many thanks for creating this plugin. I'm currently testing it out for my website. I tried changing it via permalinks, but it broke me dev website (codingbee.com). When I viewed the posts, I kept getting 404 error messages. 

I also tried using:

https://en-gb.wordpress.org/plugins/custom-post-type-permalinks/ 

But still same problems. 

Also is it possible to replace 'docs' with 'tutorials' in the urls?

By the way, if interested, I would be interested in supporting you via bountysource.com

Thanks again. 
Sher

**Comment by atozsoft** [comment]
hi,
use this https://wordpress.org/plugins/permalink-manager/

**Comment by tareq1988** [comment]
I know it's way too long to reply. But now there is a filter (`wedocs_post_type`) available to change the post type args, so you could change the **rewrite** rules.

See [Here](https://github.com/tareq1988/wedocs-plugin/blob/develop/wedocs.php#L260).
