### ISSUE TITLE
Cannot get it working

### ISSUE THREAD

**Issue by raffaeu** [tareq1988/wedocs-plugin#30]
Hi, I have installed a new Wordpress using Azure, which is available at this URL:
http://servicehubdocumentation.azurewebsites.net/

Second, I installed weDocs and configured a couple of sections and docs as shown here:
![image](https://cloud.githubusercontent.com/assets/1304736/21263816/2233b5b4-c399-11e6-9c04-e6cc53092ff5.png)

Now, I can't see anything in my home page and the tutorial doesn't really explain what I am supposed to do to get weDocs working.
Am I supposed to create an empty "home page" in wordpress with some sort of tag in it?

**Comment by puttyq** [comment]
Hey @raffaeu 

You can either create a custom home page that links to the various pages you have created or you can use the homepage shortcode as described in the [wiki](https://github.com/tareq1988/wedocs-plugin/wiki/Using-Shortcodes)

**Comment by raffaeu** [comment]
Hi @puttyq, that's what I have done and I end-up with this nice structure:
https://docs.service-hub.com/developers/

and here is how we are using wedocs
https://docs.service-hub.com/docs/api-documentation/introduction/
