### ISSUE TITLE
Tags not working

### ISSUE THREAD

**Issue by hbooo** [tareq1988/wedocs-plugin#40]
Hello, 

Tags for docs doesn't work. When I set a tag to docs, and try to reach them in order to display a list of all docs with this tag, I am redirected to tag's post instead of tag's doc so there is no results
![image](https://cloud.githubusercontent.com/assets/242125/24603472/3267b846-1861-11e7-8c00-eba40ae17b89.png)
I click on the number 2 for "to modify"
![image](https://cloud.githubusercontent.com/assets/242125/24603486/42343bf0-1861-11e7-91fd-2e1c129dd846.png)

**Comment by tareq1988** [comment]
It actually works, but only the link is broken. Have to fix it.

**Comment by hbooo** [comment]
Thanks, I will wait for an update
