### ISSUE TITLE
Add a way to customize home breadcrumb link

### ISSUE THREAD

**Issue by rubengc** [tareq1988/wedocs-plugin#43]
At this moment, there is no way to change the url of the home breadcrumb link (`wedocs_breadcrumbs` filter just let you set the text label but not the link)

For wordpress installs that are not a full docs website, the home url is redirecting to the main page and my desired workflow is to redirect it to the docs archive page (/docs)

I suggest to add `home_link` arg to customize it from this filter

**Comment by tareq1988** [comment]
In 9a11e474264d6e1ff71a0c5859ca3d2c0cce2188, a **Docs Home** page added and in d918f4f0887c20546aa4fff0242efb98a98bb44d, a filter `wedocs_breadcrumbs_html` added to customize the HTML for breadcrumb.
