### ISSUE TITLE
Add docs type and taxonomy in REST API 

### ISSUE THREAD

**Issue by hbooo** [tareq1988/wedocs-plugin#44]
Hi, 

I was trying to get tags from docs type in [Rest API](https://developer.wordpress.org/rest-api/reference/tags/) but it looks like docs type isn't exposed in Rest API.

I managed to use them by modifying this code : 
`$args = array(
            'labels'              => $labels,
            'supports'            => array( 'title', 'editor', 'thumbnail', 'revisions', ),
            'hierarchical'        => true,
            'public'              => true,
            'show_ui'             => true,
            'show_in_menu'        => false,
            'show_in_nav_menus'   => true,
            'show_in_admin_bar'   => true,
            'menu_position'       => 5,
            'menu_icon'           => 'dashicons-portfolio',
            'can_export'          => true,
            'has_archive'         => true,
            'exclude_from_search' => false,
            'publicly_queryable'  => true,
            'rewrite'             => $rewrite,
            'capability_type'     => 'post',
	   'taxonomies'          => array( 'doc_tag' )`

To this : 
`$args = array(
            'labels'              => $labels,
            'supports'            => array( 'title', 'editor', 'thumbnail', 'revisions', ),
            'hierarchical'        => true,
            'public'              => true,
            'show_ui'             => true,
            'show_in_menu'        => false,
            'show_in_nav_menus'   => true,
            'show_in_admin_bar'   => true,
            'menu_position'       => 5,
            'menu_icon'           => 'dashicons-portfolio',
            'can_export'          => true,
            'has_archive'         => true,
            'exclude_from_search' => false,
            'publicly_queryable'  => true,
            'rewrite'             => $rewrite,
            'capability_type'     => 'post',
	   'taxonomies'          => array( 'doc_tag' ), 
	   'show_in_rest' 	      => true,`
in function register_post_type() 
and this code :
`$args = array(
            'labels'                     => $labels,
            'hierarchical'               => false,
            'public'                     => true,
            'show_ui'                    => true,
            'show_admin_column'          => true,
            'show_in_nav_menus'          => true,
            'show_tagcloud'              => true,
            'rewrite'                    => $rewrite`

to this code : 
`$args = array(
            'labels'                     => $labels,
            'hierarchical'               => false,
            'public'                     => true,
            'show_ui'                    => true,
            'show_admin_column'          => true,
			'show_in_rest' => true,
            'show_in_nav_menus'          => true,
            'show_tagcloud'              => true,
            'rewrite'                    => $rewrite`
in function register_taxonomy()

Both modifications are in wedocs.php

Sorry for not making a PR, I'm not a developper and not sure on how to do a pull request

**Comment by VladoMS** [comment]
Hi,

Here is an alternative way strait from the [Wordpress Docs](https://developer.wordpress.org/rest-api/extending-the-rest-api/adding-rest-api-support-for-custom-content-types/#adding-rest-api-support-to-existing-content-types)

And my current implementation:

```php
/**
 * Add REST API support to an already registered post type.
 */
add_action( 'init', 'my_custom_post_type_rest_support', 25 );
function my_custom_post_type_rest_support() {
  global $wp_post_types;

  $post_type_name = 'docs';
  if( isset( $wp_post_types[ $post_type_name ] ) ) {
    $wp_post_types[$post_type_name]->show_in_rest = true;
    // Optionally customize the rest_base or controller class
    //$wp_post_types[$post_type_name]->rest_base = $post_type_name;
    //$wp_post_types[$post_type_name]->rest_controller_class = 'WP_REST_Posts_Controller';
  }
}
```

You can make small plugin or just shove it to the functions.php of your current theme until it`s implemented to the plugin.

Have an awesome day :)
