### ISSUE TITLE
Page Not Found

### ISSUE THREAD

**Issue by sprax2ng** [tareq1988/wedocs-plugin#50]
I recently installed weDocs Plugin 1.3.3 on wp site, i did everything correctly. However upon clicking on each Navigation or link on table of content, it returned Page not found. 
I have tried everything, please help.

**Comment by paulovsky** [comment]
@sprax2ng The same was happening to me. Set your permalinks to the post ID, save, refresh, and then set them back to your previous structure. It worked in my case.
