### ISSUE TITLE
Should be added `vue.min.js` into the packaged zip on wordpress.org (ver 1.4)

### ISSUE THREAD

**Issue by kwbtdisk** [tareq1988/wedocs-plugin#68]
On ver 1.4, this is only happen only when newly installing (not happen when updating from former ver)
Maybe you forgot to add the file `vue.min.js` into the 1.4 package :)
On my side, I renamed `vue.js` => `vue.min.js` then it worked well.

<img width="1425" alt="screenshot 2018-08-26 at 11 53 45" src="https://user-images.githubusercontent.com/2969635/44624374-939a9400-a927-11e8-8df4-9e1b3e015750.png">
<img width="343" alt="screenshot 2018-08-26 at 11 53 36" src="https://user-images.githubusercontent.com/2969635/44624375-95645780-a927-11e8-8555-2effce9c8a24.png">

**Comment by AshiqKiron** [comment]
Had to rename the file to make the plugin in the dashboard
