### ISSUE TITLE
Feature request: Add code highlighter

### ISSUE THREAD

**Issue by enventa** [tareq1988/wedocs-plugin#79]
Hey @tareq1988 !

yep, me again. Another suggestion: add code highlighter, so when documentation is about code (PHP, javascript, CSS...) it gets displayed nicely and well formatted.

May be [Prism](https://prismjs.com/) would be an option here. Below a sample of how it would look like:

![image](https://user-images.githubusercontent.com/18630142/51903083-be4bb580-23bb-11e9-92c8-5a7dd8dbe9be.png)

Thanks!

**Comment by tareq1988** [comment]
Thanks for the suggestion, but there are a bunch of syntax highlighter plugins available in wp.org repository, even prism.
