### ISSUE TITLE
Move Article to Another Section

### ISSUE THREAD

**Issue by jacobmedley** [tareq1988/wedocs-plugin#97]
Hello,
Is there a way to move an article from one section to another? Example below, if you wanted to move the shortcode article to the developer section?

example:
![image](https://user-images.githubusercontent.com/7936109/68232416-05aa4680-ffcb-11e9-81f8-9e948934d4ef.png)

**Comment by thebengalboy** [comment]
Hello @jacobmedley 

You can order articles inside the section only. It's not allowing us to move it to any other section.

Thanks

**Comment by mice777** [comment]
You can open the help page in default Wordpress page editor, and change its parent.
Or click "Use the classic UI" at bottom, and for each article, use Quick edit to change its parent even faster.
